# Unit test for rapidxml. Works with https://github.com/stablecc/make

BASE = ../../..

NAME = rapidxml_unit

#CPPFLAGS += -fpermissive -Wno-implicit-function-declaration		# required for printing library only

SRCS = main.cc

include $(BASE)/import/googletest/make.mk
include $(BASE)/import/rapidxml/make.mk

include $(BASE)/make/app.mk
