# Unit test for googletest. Works with https://github.com/stablecc/make

BASE = ../../..

NAME = gtest_all_test

CPPFLAGS += -I ..

SRCS = main.cc

include $(BASE)/import/googletest/make.mk

include $(BASE)/make/app.mk
